/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());
    private SistemaHospital sistema;

    /**
     * Creates new form MenuPrincipal
     */
   public MenuPrincipal(SistemaHospital sistema) {

    initComponents();

    this.sistema = sistema;
    
    

}
   public MenuPrincipal() {

    this(new SistemaHospital());

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPaciente = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        btnMostrarPacientes = new javax.swing.JButton();
        btnMostrarDoctores = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEditarPaciente = new javax.swing.JButton();
        btnEliminarPaciente = new javax.swing.JButton();
        btnEditarDoctor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEliminarDoctor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrarCita = new javax.swing.JButton();
        btnMostrarCitas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SISTEMA HOSPITALARIO");

        jLabel2.setText("Menú Principal");

        btnPaciente.setText("Registrar Paciente");
        btnPaciente.addActionListener(this::btnPacienteActionPerformed);

        btnDoctor.setText("Registrar Doctor");
        btnDoctor.addActionListener(this::btnDoctorActionPerformed);

        btnMostrarPacientes.setText("Mostrar Pacientes");
        btnMostrarPacientes.addActionListener(this::btnMostrarPacientesActionPerformed);

        btnMostrarDoctores.setText("Mostrar Doctores");
        btnMostrarDoctores.addActionListener(this::btnMostrarDoctoresActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        btnEditarPaciente.setText("Editar Paciente");
        btnEditarPaciente.addActionListener(this::btnEditarPacienteActionPerformed);

        btnEliminarPaciente.setText("Eliminar Paciente");
        btnEliminarPaciente.addActionListener(this::btnEliminarPacienteActionPerformed);

        btnEditarDoctor.setText("Editar Doctor");
        btnEditarDoctor.addActionListener(this::btnEditarDoctorActionPerformed);

        jLabel4.setText("PACIENTES");

        jLabel5.setText("DOCTORES");

        btnEliminarDoctor.setText("Eliminar Doctor");
        btnEliminarDoctor.setToolTipText("");
        btnEliminarDoctor.addActionListener(this::btnEliminarDoctorActionPerformed);

        jLabel3.setText("CITAS");

        btnRegistrarCita.setText("Registrar Cita");
        btnRegistrarCita.addActionListener(this::btnRegistrarCitaActionPerformed);

        btnMostrarCitas.setText("Mostrar Citas");
        btnMostrarCitas.addActionListener(this::btnMostrarCitasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4)
                .addGap(280, 280, 280)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarCita, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(btnMostrarCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEditarDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                            .addComponent(btnMostrarDoctores, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegistrarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnEliminarDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMostrarDoctores, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnMostrarPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        // TODO add your handling code here:
      RegistrarPaciente ventana = new RegistrarPaciente(sistema);

      ventana.setVisible(true);
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
        int opcion = JOptionPane.showConfirmDialog(
        this,
        "¿Desea salir del sistema?",
        "Salir",
        JOptionPane.YES_NO_OPTION
);

if(opcion == JOptionPane.YES_OPTION){

    System.exit(0);

}
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
        
        RegistrarDoctor ventana = new RegistrarDoctor(sistema);

        ventana.setLocationRelativeTo(null);

        ventana.setVisible(true);
        
        //this.dispose();

System.out.println("Botón Registrar Doctor presionado.");
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnMostrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPacientesActionPerformed
        // TODO add your handling code here:
        MostrarPacientes ventana = new MostrarPacientes(sistema);

        ventana.setLocationRelativeTo(null);

        ventana.setVisible(true);
    }//GEN-LAST:event_btnMostrarPacientesActionPerformed

    private void btnMostrarDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDoctoresActionPerformed
        // TODO add your handling code here:
        
         MostrarDoctores ventana = new MostrarDoctores(sistema);

            ventana.setLocationRelativeTo(null);

            ventana.setVisible(true);
    }//GEN-LAST:event_btnMostrarDoctoresActionPerformed

    private void btnEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPacienteActionPerformed
        // TODO add your handling code here:
        
        EditarPaciente ventana = new EditarPaciente(sistema);

        ventana.setLocationRelativeTo(null);

        ventana.setVisible(true);

    }//GEN-LAST:event_btnEditarPacienteActionPerformed

    private void btnEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPacienteActionPerformed
        // TODO add your handling code here:
        
        EliminarPaciente ventana = new EliminarPaciente(sistema);

        ventana.setLocationRelativeTo(null);

        ventana.setVisible(true);
        
    }//GEN-LAST:event_btnEliminarPacienteActionPerformed

    private void btnEditarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDoctorActionPerformed
        // TODO add your handling code here:
        
        EditarDoctor ventana = new EditarDoctor(sistema);

        ventana.setLocationRelativeTo(null);

        ventana.setVisible(true);
        
    }//GEN-LAST:event_btnEditarDoctorActionPerformed

    private void btnEliminarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDoctorActionPerformed
        // TODO add your handling code here:
        
        
        EliminarDoctor ventana = new EliminarDoctor(sistema);

        ventana.setLocationRelativeTo(null);

        ventana.setVisible(true);

    }//GEN-LAST:event_btnEliminarDoctorActionPerformed

    private void btnRegistrarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCitaActionPerformed
        // TODO add your handling code here:
        
        RegistrarCita ventana = new RegistrarCita(sistema);

        ventana.setLocationRelativeTo(null);

        ventana.setVisible(true);
    }//GEN-LAST:event_btnRegistrarCitaActionPerformed

    private void btnMostrarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCitasActionPerformed
        // TODO add your handling code here:
        
        MostrarCitas ventana = new MostrarCitas(sistema);

        ventana.setLocationRelativeTo(null);

        ventana.setVisible(true);

        
    }//GEN-LAST:event_btnMostrarCitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnEditarDoctor;
    private javax.swing.JButton btnEditarPaciente;
    private javax.swing.JButton btnEliminarDoctor;
    private javax.swing.JButton btnEliminarPaciente;
    private javax.swing.JButton btnMostrarCitas;
    private javax.swing.JButton btnMostrarDoctores;
    private javax.swing.JButton btnMostrarPacientes;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JButton btnRegistrarCita;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
